### ISSUE TITLE
Cannot pip install patton-cli

### ISSUE THREAD

**Issue by pealtrufo** [BBVA/patton-cli#6]
I cannot pip install patton-cli. I am getting this error:
    KeyError: 'CIRCLE_BUILD_NUM'

It seems that this env variable is required for the installation but I cannot see anything in the documentation to understand why that is required.

Thanks!

**Comment by paralax** [comment]
a workaround is to set it in your env, e.g. in `bash` or `zsh` just do this: `export CIRCLE_BUILD_NUM=1.0; pip3 install ...`

**Comment by jjelosua** [comment]
Same issue here, it seems that the latest code on master has not been uploaded to pypi specifically this commit 87a9ea86cbc32fe2f0f671b5e8f44f04d56b15e3
